# Nombre del flujo de trabajo, aparecerá en la pestaña "Actions" de GitHub
name: Ejecutar Pronóstico de Demanda Diario

# Define cuándo se debe ejecutar este flujo
on:
  # Permite ejecutarlo manualmente desde la pestaña "Actions"
  workflow_dispatch:
  
  # Define un horario programado
  schedule:
    # Formato CRON: Minuto Hora Día Mes DíaDeLaSemana
    # '0 10 * * *' se ejecuta todos los días a las 10:00 UTC.
    # Esto corresponde a las 6:00 AM en Chile (UTC-4) durante el invierno.
    # Ajusta la hora según tus necesidades.
    - cron: '0 10 * * *'

# Define los trabajos (jobs) que se ejecutarán
jobs:
  # Nombre del trabajo
  build-and-forecast:
    # La máquina virtual que se usará. 'ubuntu-latest' es estándar y gratuita.
    runs-on: ubuntu-latest

    # Los pasos que se ejecutarán en orden
    steps:
      # 1. Descarga tu código desde el repositorio a la máquina virtual
      - name: Checkout del código
        uses: actions/checkout@v3

      # 2. Configura el entorno de Python
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # Asegúrate que coincida con tu versión de Python

      # 3. Instala todas las librerías necesarias
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Ejecuta el pipeline principal
      - name: Ejecutar el pipeline de pronóstico
        # Aquí es donde le pasamos el secreto a nuestro script
        env:
          GSPREAD_CREDENTIALS: ${{ secrets.GSPREAD_CREDENTIALS }}
        run: python main.py
