name: Weekly Demand Forecast

on:
  workflow_dispatch:
  schedule:
    # Ejecuta cada lunes a las 12:00 PM UTC, que corresponde a las 8:00 AM en Chile (UTC-4).
    # ¡Importante! Ten en cuenta los cambios de horario de verano/invierno en Chile.
    # Si Chile cambia a UTC-3 (horario de verano), 8 AM CL sería 11 AM UTC.
    # Sin embargo, la ejecución en UTC es consistente.
    - cron: '0 12 * * MON'

jobs:
  run_forecast:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # Asegúrate que coincida con tu versión de Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy prophet gspread gspread-dataframe oauth2client

    - name: Run Demand Forecast Script # ¡Aquí está el cambio!
      env:
        # Nombre del secreto de credenciales
        GSPREAD_CREDENTIALS: ${{ secrets.GSPREAD_CREDENTIALS }}
      run: |
        # ¡CAMBIO AQUÍ! Ejecutando pronostico_demanda_semanal.py que está en la carpeta 'modelo/'
        python modelo/pronostico_demanda_semanal.py
